git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# fall back theme in case terminal app not configured
gui:
  showFileTree: true
  theme:
    activeBorderColor:
    - '#fab387'
    - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#fab387'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
