"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:surface0)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$lua\
$kotlin\
$haskell\
$python\
[ ](fg:surface0)\
$line_break\
$character
"""

right_format = """
$cmd_duration\
[](black)\
$battery\
[](fg:black bg:surface0)\
$time\
[](surface0)\
"""

follow_symlinks = true
add_newline = true
palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[time]
disabled = false
time_format = "%R"
style = "bg:surface0"
format = '[[  $time ](fg:mantle bg:surface0)]($style)'

[battery]
disabled = false
format = "[[$symbol$percentage ](fg:base bg:black)]($style)"
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol = '󰁽 '
empty_symbol = '󰂎 '

[[battery.display]]
style = "black"
threshold = 20 
discharging_symbol = '󰂎 '

[[battery.display]]
style = "black"
threshold = 60 
discharging_symbol = '󰁽 '

[[battery.display]]
style = "black"
threshold = 100 
discharging_symbol = '󰁹 '


[cmd_duration]
disabled = false
min_time = 1000
style = "black"
format = '[$duration]($style) ' 

[os]
disabled = false
style = "bg:surface0 fg:text"
[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
# Macos = " "
Macos = " "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false 
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "
"Dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:crust bg:green)]($style)'

[nodejs]
disabled = true
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[c]
symbol = " "
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[rust]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[golang]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[php]
disabled = true
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[java]
symbol = " "
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[lua]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[kotlin]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[haskell]
disabled = true
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[python]
disabled = true
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $version) ](fg:crust bg:surface0)]($style)'

[docker_context]
disabled = true 
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:crust bg:teal)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

vimcmd_symbol = '[❮](bold fg:blue)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:peach)'
